services:
  runners:
    image: quay.io/necronizerslab/runner:0.25.26
    env_file:
      - runner.env
    networks:
      - k3d_network

networks:
  k3d_network:
    name: k3d-cloud
    external: true
