name: Build and store GitHub Actions Runner Image

on:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build.yml
  pull_request:
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  build_push_image:
    name: Building and storing YASM Runner Docker Image
    uses: necro-cloud/automations/.github/workflows/build-docker-image.yml@main
    with:
      dev_version_name: development
      image_name: runner
      image_proper_name: Self Hosted GitHub Runner
      build_path: .
      repository: yasm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
