name: Build and store GitHub Actions Runner Image

on:
  push:
    branches:
      - feature/**
      - bug/**
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build.yml
  pull_request:
    paths:
      - Dockerfile
      - docker-entrypoint.sh
      - .github/workflows/build.yml
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  build_push_image:
    name: Building and storing PhotoAtom Runner Docker Image
    uses: PhotoAtom/automations/.github/workflows/build-docker-image.yml@feature/22/secret-select
    with:
      dev_version_name: dev
      image_name: runner
      image_proper_name: PhotoAtom Runner
      build_path: .
      repository: necronizerslab
    secrets: inherit
