name: Test Communication with Self Hosted Kubernetes Cluster

on:
  workflow_dispatch:

jobs:
  test_communication:
    name: Testing Communication with Self Hosted Kubernetes Cluster
    runs-on: [self-hosted, linux, cloud]
    env:
      KUBECONFIG: '/tmp/kubernetes/config.yml'
      KUBECONFIG_FOLDER: '/tmp/kubernetes'
    steps:
      - name: Create and save KubeConfig file
        run: |

          # Create the folder for KubeConfig file
          mkdir -p ${{ env.KUBECONFIG_FOLDER }}

          # Save the KubeConfig file
          echo '${{ secrets.KUBECONFIG }}' >> ${{ env.KUBECONFIG }}

      - name: Run KubeCTL Commands to check communication with the local Kubernetes cluster
        run: kubectl get ns
